[package]
name = "ttdal-py"
version = { workspace = true }
edition = { workspace = true }
rust-version = { workspace = true }
description = { workspace = true }
publish = false

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lib]
name = "ttdal"
crate-type = ["cdylib"]
test = false
doc = false

[dependencies]
libc = { workspace = true }
pyo3 = { version = "0.29", features = ["abi3-py310", "extension-module", "multiple-pymethods"] }
ttdal-sys = { workspace = true }
