[build-system]
requires = ["maturin>=1.9.4,<2.0"]
build-backend = "maturin"

[project]
name = "ttdal"
readme = "README.md"
requires-python = ">=3.10"
license = "Apache-2.0"
license-files = ["LICENSE", "NOTICE"]
keywords = ["tenstorrent", "accelerator", "hardware", "driver"]
classifiers = [
    "Development Status :: 3 - Alpha",
    "Intended Audience :: Developers",
    "Operating System :: POSIX :: Linux",
    "Programming Language :: Python :: 3",
    "Programming Language :: Rust",
    "Topic :: System :: Hardware",
]
dependencies = ["semver>=3.0.4"]
dynamic = ["version", "description"]

[project.urls]
Repository = "https://github.com/tenstorrent/tt-dal"

[tool.maturin]
sdist-generator = "git"
