[package]
name = "ttdal"
version = { workspace = true }
edition = { workspace = true }
description = { workspace = true }
publish = false

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
libc = { workspace = true }
pci = { path = "crates/pci" }
semver = "1.0.27"
ttdal-sys = { workspace = true }

[dev-dependencies]
serial_test = "3.4.0"
