[package]
name = "ttdal"
version = { workspace = true }
edition = { workspace = true }
rust-version = { workspace = true }
description = { workspace = true }
readme = "README.md"
repository = { workspace = true }
publish = false
keywords = ["tenstorrent", "accelerator", "hardware", "driver", "ffi"]
categories = ["hardware-support", "api-bindings"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
libc = { workspace = true }
semver = "1.0.28"
ttdal-sys = { workspace = true }

[dev-dependencies]
serial_test = "4.0.1"
